const path = require('path');
const express = require('express');
const rootDirectory = require('../utilities/path');

//get products array generated by admin.js
const adminData = require('./admin');

//to use the code from this file in server.js
const router = express.Router();

router.get('/', function(req, res){
    const products = adminData.products;
    
    //console.log("Hello from shop.js ", products);
    
    res.render('shop', {
        pageTitle: "Welcome!",
        pageWelcome: "Welcome to My Shop!",
        path: "/",
        listOfProducts: products
    });
    //res.sendFile(path.join(rootDirectory, 'views', 'shop.html'));
});

module.exports = router;